name: custom_reorderable_list
description: A highly customizable reorderable list widget for Flutter with drag-and-drop functionality, visual feedback, and auto-scrolling.
version: 1.0.0
homepage: https://github.com/AbdY-G/ReorderableV2.0
repository: https://github.com/AbdY-G/ReorderableV2.0.git
issue_tracker: https://github.com/AbdY-G/ReorderableV2.0/issues

environment:
  sdk: ^3.9.2
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: